import UiIcon from './UiIcon';

type PriceOption = { category: string; duration: string; name: string; description: string; price: number; ctaLabel: string; smsBody: string; bestFor: string; includes: string[]; scopeNote: string; featured?: boolean; compact?: boolean };
const message = (offer: string) => `sms:+13528750467?body=${encodeURIComponent(`Hi Sean, I'd like help with ${offer}.`).replace(/'/g, '%27')}`;
const options: PriceOption[] = [
  { category: 'REMOTE', duration: '15 MIN', name: 'Quick Fix', description: 'A focused remote session for one clear issue.', price: 20, ctaLabel: 'Request this session', smsBody: message('a Quick Fix'), bestFor: 'One simple question or setting check.', includes: ['One device', 'Up to 15 minutes', 'A clear next step'], scopeNote: 'Stops at 15 minutes. A larger or multi-step issue needs a separately agreed session.', featured: true },
  { category: 'REMOTE', duration: '60 MIN', name: 'Remote Tune-Up', description: 'Troubleshooting, setup, or a guided cleanup.', price: 65, ctaLabel: 'Request this session', smsBody: message('a Remote Tune-Up'), bestFor: 'One focused troubleshooting, setup, or guided-cleanup task.', includes: ['Up to 60 minutes by phone or temporary visible remote session', 'Plain-English explanation'], scopeNote: 'Customer stays present and enters credentials. A new issue requires new scope.' },
  { category: 'IN PERSON', duration: '60 MIN', name: 'In-person Tune-Up', description: 'Hands-on support for your home technology.', price: 85, ctaLabel: 'Request this session', smsBody: message('an In-person Tune-Up'), bestFor: 'One focused home-technology issue at an agreed location.', includes: ['Up to 60 minutes', 'Explanation and next step'], scopeNote: 'Service area, travel, and availability are confirmed before booking. No electrical or life-safety work.' },
  { category: 'GUIDANCE', duration: '60 MIN', name: 'Digital Confidence', description: 'Patient one-on-one learning.', price: 55, ctaLabel: 'Request this session', smsBody: message('Digital Confidence'), bestFor: 'Guided learning for one app, account, tool, or workflow.', includes: ['Up to 60 minutes', 'Questions and practice at your pace'], scopeNote: 'Guidance only; Sean does not take control of sensitive accounts or credentials.', compact: true },
  { category: 'HOME', duration: '90 MIN', name: 'Home Technology Reset', description: 'A deeper review and reset.', price: 125, ctaLabel: 'Request this session', smsBody: message('a Home Technology Reset'), bestFor: 'One planned household setup covering agreed devices, Wi-Fi basics, backup organization, or digital organization.', includes: ['Up to 90 minutes'], scopeNote: 'One agreed scope. No guaranteed data recovery, electrical work, malware/breach response, or emergency support.', compact: true },
  { category: 'FOLLOW-UP', duration: '30 MIN', name: 'Office Hours', description: 'Keep momentum after a session.', price: 35, ctaLabel: 'Request this session', smsBody: message('Office Hours'), bestFor: 'Remote follow-up on the same previously approved scope.', includes: ['Up to 30 minutes', 'Remaining questions and next step'], scopeNote: 'A new or materially different problem requires a newly agreed session.', compact: true },
];

type PricingGridProps = { detailed?: boolean };
export default function PricingGrid({ detailed = false }: PricingGridProps): React.ReactNode {
  return <div className="price-grid">{options.map((option) => <article className={`price-card${option.featured ? ' featured-price' : ''}${option.compact ? ' compact-price' : ''}`} key={option.name}>
    <div className="price-top"><span>{option.category}</span><i>{option.duration}</i></div><h3>{option.name}</h3><p>{option.description}</p>{detailed && <div className="price-detail"><strong>Best for</strong><p>{option.bestFor}</p><strong>Includes</strong><ul>{option.includes.map((item) => <li key={item}>{item}</li>)}</ul><strong>Scope note</strong><p>{option.scopeNote}</p></div>}<strong><sup>$</sup>{option.price}</strong><a href={option.smsBody}>{option.ctaLabel} <UiIcon name="up-right" /></a>
  </article>)}</div>;
}
